[project]
name = "eq-backtest"
version = "0.1.0"
description = "Equity Cross-sectional Strategy Backtest"
readme = "doc/README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "numpy",
    "numba",
    "matplotlib",
    "polars",
    "pyarrow>=23.0.1",
    "fastparquet>=2026.3.0",
    "loguru>=0.7.3",
    "openpyxl>=3.1",
    "pyyaml>=6.0",
]



[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"

[tool.uv.workspace]
members = [
    "backtest_verify",
]
