[project]
name = "bt-daily"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "numpy",
    "numba",
    "matplotlib",
    "polars",
    "pyarrow>=23.0.1",
    "fastparquet>=2026.3.0",
    "loguru>=0.7.3",
    "pyyaml>=6.0",
]



[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"

[tool.uv.workspace]
members = [
    "backtest_verify",
]
